# Generated by Django 2.0.5 on 2018-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0003_auto_20180522_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='mar',
            field=models.IntegerField(null=True),
        ),
    ]
