# Generated by Django 2.0.5 on 2018-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0004_emp_mar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='excellent',
            field=models.BooleanField(default=0, verbose_name='是否优秀'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='dno',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='部门编号'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='location',
            field=models.CharField(max_length=10, verbose_name='部门所在地'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='name',
            field=models.CharField(max_length=20, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='comm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='mar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
